# Site settings
title: Volkan Sahin's CV 
description: Volkan Sahin's CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: cv.volkansah.in
rss_url: /pages/atom.xml
#google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Volkan Sahin
  title: Software Developer
  address: Ankara, Turkey
  email: bm.volkansahin@gmail.com
  link: volkansah.in
  weibo:
  github: volkansahin
  linkedin: volkansahin
  twitter: volkansahin
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: AGEM Bilisim
      location: Ankara, Turkey
      title: Full Stack Software Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
   - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Northeastern University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
