# Site settings
title: Volkan Sahin's CV 
description: Volkan Sahin's CV
favicon: /assets/img/volkan.png
baseurl: 
url: 
rss_url: /pages/atom.xml
# google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Volkan Sahin
  title: Software Developer
  address: Ankara, Turkey
  email: bm.volkansahin@gmail.com
  link: volkansah.in
  weibo:
  github: volkansahin
  linkedin: volkansahin
  twitter: volkansahin
  gavatar: /assets/img/volkan.png
 # stackoverflow: 1287752
  workHistory:
    - work1:
      company: <b>LAWA</b>
      location: Ankara, Turkey
      title: Backend Developer
      started: 2016
      duration: (2016 - Present)
      description: The current Lider Ahenk is a solution that manages Linux clients only. Open source, general public license (GPL) and innovative product developed using internationally known, competitive, ar-ge based, fully open standards, open source code solutions, which can manage Windows clients with the LAWA (Lider Ahenk Windows Agent) project.
    - work2:
      company: <b>Lider Ahenk</b>
      location: Ankara, Turkey
      title: Backend Developer
      started: 2015
      duration: (2015 - 2016)
      description: LiderAhenk is an open-source software application developed for TÜBİTAK ULAKBİM (The Scientific and Technological Research Council of Turkey - Turkish Academic Network and Information Center), which provides managing, monitoring and controlling the large amounts of systems and their users on the institutional network through a single point. <b>liderahenk.org</b>
    - work3:
      company: <b>ARYA</b>
      location: Ankara, Turkey
      title: Full Stack Developer
      started: 2014
      duration: (2014-2015)
      description: Development of new applications for next generation platforms and part of the migration methodology and supporting solution components of existing applications.Arya offers a fast and effective solution platform for supporting existing software applications, next-generation web browsers, Android and IOS-based smartphones and tablets, and Linux-based desktop platforms. <b>aryaportal.org</b>
    - work4:
      company: <b>RCOP MIS</b>
      location: Ankara, Turkey
      title: Full Stack Developer
      started: 2014
      duration: (2014)
      description: The Regional Competitiveness Operational Program (RCOP) has been carried out since 2007 in the context of the financial cooperation agreement between Turkey and the European Union. It is included in the development strategy of Turkey. Financial services and support services. RCOP has been developed with MIS application to manage RCOP processes.
  educationHistory:
    - education1:
      organization: Hacettepe University
      location: Ankara, Turkey
      degree: Bachelor
      major: Computer Engineering
      started: 2009
      duration: (2009 - 2014)
      description: Competitions I have attended throughout my university life include;<ul><li><b>2014 TUBITAK License Software Projects Competition (2242)</b>We found the opportunity to introduce our project in TUBITAK exhibition space by entering the top 13 in Turkey with software (Saglik Bekcisi) and Smart and Technological Solutions categories that we developed to prevent health problems arising from computer use for a long time by using image processing and gaming technologies.</li><li><b>2014 Hacettepe Engineering Faculty</b>We have attained the second year of Computer Engineering with the project of Health Career by participating in the project exhibition where the graduation projects of engineering students are held.</li><li><b>2014 Cozum Kumbarasi</b>In Cozum Kumbarasi, a social innovation competition realized by Intel, our project was among the first 40 projects called for in Phase 2 throughout Turkey.</li><li><b>2013 PILOTT Türk Telekom Initiative Acceleration Program</b>, Speed Call, which aims to reduce the access time to call centers, entered the race with 10% slope in Turkey (first 40) and we interviewed Istanbul TT Office face to face.</li><li><b>2013 Boğaziçi University Enterprice Entrepreneurship Competition</b> In the entrepreneurship competition, we were chosen among the 50 groups that survived to the second stage (10% slice) with our survey-focused social network. We handed out the Project's Business Canvas model.</li></ul>

  languages:
    - language1:
      name: Turkish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Python
      percentage: 100%
    - skill3:
      name: JavaScript
      percentage: 100%
    - skill4:
      name: C#
      percentage: 90%
    - skill5:
      name: C/C++
      percentage: 80%
  familiarTechnologies:
    - tech1:
      name: XMPP(Ejabberd) <b>|</b> LDAP(OpenLDAP) <b>|</b> Eclipse RCP <b>|</b> OSGI (Karaf) <b>|</b> Apache Tomcat
    - tech2:
      name: Maven <b>|</b> Gradle  <b>|</b> Git <b>|</b>SVN  <b>|</b> Jenkins
    - tech3:
      name: Postgresql<b>|</b> MySQL  <b>|</b> MariaDB <b>|</b> SQLite 
    - tech4:
      name: Eclipse<b>|</b> PyCharm <b>|</b>  Android Studio <b>|</b> Visual Studio <b>|</b> NetBeans <b>|</b> CodeBlocks

    - tech5:
      name: IBM WebSphere Business Modeller<b>|</b> Visual Paradigm <b>|</b>  Android Studio <b>|</b> Visual Studio <b>|</b> PgAdmin <b>|</b> MySQL Workbench

