# Site settings
title: Volkan Sahin's CV 
description: Volkan Sahin's CV
favicon: /assets/img/volkan.png
baseurl: 
url: 
rss_url: /pages/atom.xml
# google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Volkan Sahin
  title: Software Developer
  address: Ankara, Turkey
  email: bm.volkansahin@gmail.com
  link: volkansah.in
  weibo:
  github: volkansahin
  linkedin: volkansahin
  twitter: volkansahin
  gavatar: /resumecard/assets/img/avatar.JPG
 # stackoverflow: 1287752
  workHistory:
    - work1:
      company: Lider Ahenk
      location: Ankara, Turkey
      title: Full Stack Developer
      started: 2014
      duration: (2014 - Present)
      description: LiderAhenk is an open-source software application developed for TÜBİTAK ULAKBİM (The Scientific and Technological Research Council of Turkey - Turkish Academic Network and Information Center), which provides managing, monitoring and controlling the large amounts of systems and their users on the institutional network through a single point.
  educationHistory:
    - education1:
      organization: Hacettepe University
      location: Ankara, Turkey
      degree: Bachelor
      major: Computer Engineering
      started: 2009
      duration: (2009 - 2014)
  languages:
    - language1:
      name: Turkish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Python
      percentage: 100%
    - skill3:
      name: JavaScript
      percentage: 100%
    - skill4:
      name: AngularJS
      percentage: 70%
